basePath: /
host: localhost:18181
info:
  contact: {}
  title: IMBiz Swagger API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Get Hello Test
      produces:
      - application/json
      responses:
        "200":
          description: Hello, IMBIZ!
          schema:
            type: string
      summary: Get Hello
  /mysql/create:
    post:
      consumes:
      - application/json
      description: POST Mysql Create
      parameters:
      - description: text
        in: body
        name: TEXT
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: POST Mysql Create
  /mysql/delete:
    delete:
      consumes:
      - application/json
      description: DELETE Mysql Delete
      parameters:
      - description: index
        in: body
        name: INDEX
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: DELETE Mysql Delete
  /mysql/read:
    get:
      consumes:
      - application/json
      description: GET Mysql Create
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                additionalProperties: true
                type: object
              type: array
            type: array
      summary: GET Mysql Create
  /mysql/update:
    put:
      consumes:
      - application/json
      description: PUT Mysql Update
      parameters:
      - description: text
        in: body
        name: TEXT
        required: true
        schema:
          type: string
      - description: index
        in: body
        name: INDEX
        required: true
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: PUT Mysql Update
  /userinfo/create:
    post:
      consumes:
      - application/json
      description: Create User
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Create User
      tags:
      - User
  /userinfo/delete:
    delete:
      consumes:
      - application/json
      description: Delete User
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Delete User
      tags:
      - User
  /userinfo/login:
    post:
      consumes:
      - application/json
      description: Login
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Login
      tags:
      - Login
  /userinfo/logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Logout
      tags:
      - Login
  /userinfo/read:
    get:
      consumes:
      - application/json
      description: Read User
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Read User
      tags:
      - User
  /userinfo/update:
    put:
      consumes:
      - application/json
      description: Update User
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Update User
      tags:
      - User
swagger: "2.0"
